### ISSUE TITLE
Schedule window - Specify last trip in period

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#800] opened 2023-12-06 16:39 UTC
When building a schedule, Transition enables the user to specify the time of the first trip in a given period.

However, it is impossible to specify the time of the last trip in a period. This generates an issue with the last period of the day, since it stretches until 28:00 while regular service often stops before that. For lines with limited service during the day (short versions, peak-only lines). it can also limit the user in building a service that looks like the real service.

Hence, Transition should enable the user to set a first *and* a last time within a service period.

Allowing the edition of trips in a service, or the insertion of custom trips (see issue #126), could be useful as a workaround.

**Comment by tahini** [comment] 2023-12-21 13:42
Duplicate of #337, which was fixed earlier this week

**Closed by tahini** 2023-12-21 13:42 UTC
