### ISSUE TITLE
Path: routing: allow different routing engines or travel times per period or specific trips using osm start/end nodes csv files

### ISSUE THREAD

**Issue by kaligrafy** [chairemobilite/transition#548] opened 2023-01-25 18:46 UTC
This will make it possible to include routing engine with traffic data for each period of the day or each day of the week.

**Comment by kaligrafy** [comment] 2023-03-07 16:53
See [OSRM wiki page on Traffic updates](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic)

**Comment by kaligrafy** [comment] 2023-03-07 16:54
It seems we need to call contract again for each update. You can call contract with speedups params, but it will slow down routing queries. So this needs some testing.

**Comment by kaligrafy** [comment] 2023-03-07 16:54
For now, it would also mean we need to start one unique OSRM server for each period of the day we want to include a csv file.

**Comment by kaligrafy** [comment] 2023-03-07 16:55
We should be able to import a CSV file with start/end nodes and custom speeds inside transition somewhere.

**Comment by tahini** [comment] 2024-01-31 19:18
duplicate of #591

**Closed by tahini** 2024-01-31 19:18 UTC
Labels: enhancement, osrm, openstreetmap
