### ISSUE TITLE
Schedules: Batch add schedules for a service at x minutes

### ISSUE THREAD

**Issue by tahini** [chairemobilite/transition#526] opened 2023-01-19 15:44 UTC
Say we want to generate schedules at every X minutes for a set of lines.

It should be possible to batch select lines and generate a schedule at interval X, associated with a service.

The selected lines should not have a schedule already defined for the service. Otherwise, ask the user to confirm if he wants to override the current schedule.

**Comment by greenscientist** [comment] 2023-01-20 19:22
Is this the same as #292 ?

**Comment by kaligrafy** [comment] 2023-07-24 17:25
DUplicate of #292

**Closed by kaligrafy** 2023-07-24 17:25 UTC
Labels: enhancement
