### ISSUE TITLE
Account for hourly variations in trip durations when building the stop times

### ISSUE THREAD

**Issue by tibobliss** [chairemobilite/transition#801] opened 2023-12-06 16:53 UTC
In real-world conditions, a given bus line's total trip time can vary according to the time of the day and the driving conditions. 

When building a bus line from scratch, it is impossible to introduce this kind of variation since a single speed can be calibrated for each path.

This limits the use of Transition's route calculator to reliably assess travel time improvements throughout a day. The user is forced to simulate a single period in the day (i.e. peak or off-peak) if they want to use realistic travel times, which negates the usefulness of a full-day schedule.

**Comment by tahini** [comment] 2024-01-31 19:18
Also duplicate of #591

**Closed by tahini** 2024-01-31 19:18 UTC
